# Generated by Django 3.0.7 on 2021-01-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210109_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo_21',
            new_name='car_photo_2',
        ),
    ]
